row_length: 3.5
row_width: 0.95
rows_count: 7
row_segments: 
  - straight
plant_spacing_min: 0.06
plant_spacing_max: 0.13
plant_height_min: 0.6
plant_height_min: 1.2
plant_radius: 0.06
hole_prob: 0.04
hole_size_max: 7
ground_resolution: 0.1
